name: daniel_mcerlean_project_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  html: ^0.15.4
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon3.png"

flutter:
  uses-material-design: true
  assets:
    - assets/documentation.html
    - assets/style.css
    - assets/images/
